패키지 구조 세팅 및 실행 환경 구성
BENTO-o/backend pull request #2
Opened 2024-10-12 15:33 UTC by yes-ee

## 🔍 What is this PR?

- api 개발을 위한 패키지 구조를 세팅하고, db 환경변수를 설정했습니다.

## 📝 Changes

- 패키지 구조 세팅
  - [계층형 구조](https://ksh-coding.tistory.com/96) 선택
  - oauthprovider enum 클래스로 분리
- 예시 api 추가
  - `/users/test`
- 실행 환경 구성
  - docker-compose 파일에 db 정보 세팅
  - 환경변수 .env 파일로 분리
  - password 파일 삭제
- 초기 데이터 설정 파일 추가

## ✔️ CheckList

- [ ] docker-compose로 정상 실행되는지 확인
- [ ] mysql 내부에 database, table 생성되었는지 확인

2024-10-13 08:49 UTC, leesiha approved these changes

2024-10-13 08:49 UTC, leesiha commented on backend/src/main/java/bento/backend/service/UserService.java
> +
`import bento.backend.domain.User;` 가 포함되어 있지 않으면 User entity를 찾지 못해 실행되지 않습니다.

2024-10-13 08:49 UTC, leesiha commented on docker-compose.yaml
>      restart: always
주석처리 해 두는 것이 좋겠습니다.
사유 : 중간에 에러가 발생해도 무한 재시작하게 돼서 로그 기반 디버깅 하기 어려움

2024-10-13 08:50 UTC, leesiha requested changes
기존에 작성해둔 리뷰 참고하셔서 코드 수정해주세요!

2024-10-14 11:32 UTC, yes-ee commented on docker-compose.yaml
>      restart: always
수정 완료!

2024-10-14 13:42 UTC, leesiha approved these changes

2024-10-15 09:13 UTC, merged